### ISSUE TITLE
New Task #3 in Teamwork - 7 - https://api.github.com/repos/NETESOLUTIONS/test-integration/issues/7 - 139017962 - 10 - https://api.github.com/repos/NETESOLUTIONS/test-integration/issues/10 - 139019730 - 12 - https://api.github.com/repos/NETESOLUTIONS/test-integration/issues/12 - 139021521

### ISSUE THREAD

**Issue by M00staff** [NETESOLUTIONS/test-integration#19]
Task Number 3 - code stuff  

2016-03-07T16:09:21Z  

color: ededed
name: False
url: https://api.github.com/repos/NETESOLUTIONS/test-integration/labels/False  

2016-03-07T16:15:05Z  

2016-03-07T16:20:41Z

**Comment by tiffanynete** [comment]
comment 3/7 at 1135am
